import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import TheHeader from "@/widgets/TheHeader";
import TheFooter from "@/widgets/TheFooter";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
      <div className="relative flex size-full min-h-screen flex-col bg-[#122118] dark group/design-root overflow-x-hidden">
          <div className="layout-container flex h-full grow flex-col">
              <TheHeader/>
              {children}
              {/*<TheFooter/>*/}
          </div>
      </div>
      </body>
    </html>
  );
}
